### ISSUE TITLE
Loss of discoverd connection

### ISSUE THREAD

**Issue by miracle2k** [flynn-archive/go-discoverd#13]
I encountered this with sdutil, but I presume it affects any client; if the discoverd host goes away, any client connecting to it will stop interacting with service discovery, does not appear to recover, but neither will it crash.

There are at two sides to this as far as I can see: 

1) A service will stop sending heartbeats.
2) A service will stop getting updates.

Is there a plan for this? Should a graceful reconnect feature be added to the discoverd client library?

**Comment by titanous** [comment]
Yeah, we need reconnect and error handling so that this is handled.

**Comment by progrium** [comment]
I'm pretty sure Duplex will help a lot with this, so we might want to punt for now.
