### ISSUE TITLE
nil updates from Leaders()

### ISSUE THREAD

**Issue by Qard** [flynn-archive/go-discoverd#22]
I'm getting issues from go-flynn in flynn-controller and flynn-receiver that all seem to trace back to Leaders() sometimes returning nil updates, while go-flynn doesn't have any handling for that.

see: https://github.com/flynn/go-flynn/blob/master/cluster/client.go#L37, https://github.com/flynn/go-discoverd/blob/master/client.go#L220

For the time being, I've patched go-flynn myself by continuing in followLeaders() if the update is nil, but there's probably a better way to fix that.

**Comment by titanous** [comment]
`nil` indicates that there are no servers left in the cluster. It should probably be better documented, and I'll fix in go-flynn.

**Comment by Qard** [comment]
Ah. Yeah, I was getting issues from that at startup. Probably servers not
available yet. Putting in the continue on nil made the retry logic work
though.

**Comment by titanous** [comment]
This should be solved by flynn/go-flynn@8dac788a7d0425faf11071cbab7090b61a210f3b.
