### ISSUE TITLE
Handle and document leader demotion

### ISSUE THREAD

**Issue by titanous** [flynn-archive/go-discoverd#28]
This can happen if there is a glitch in the heartbeats and another instance get promoted.

**Comment by progrium** [comment]
Do you have more details?

On Tue, Apr 8, 2014 at 3:59 PM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> This can happen if there is a glitch in the heartbeats and another
> instance get promoted.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/go-discoverd/issues/28
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
Yep, if a heartbeat gets delayed until after the TTL expires (for example due to excessive load), the key will reappear with a new `createdIndex` on the next heartbeat. If this happens, the old leader will still think it's the leader (unless it knows this can happen and demotes itself) and a new leader will be elected.

This is one of the ways systems that depend on discoverd could end up with split brain.

**Comment by titanous** [comment]
Detection of this can be accomplished via flynn/discoverd#41.
