### ISSUE TITLE
DISCOVERD env var format

### ISSUE THREAD

**Issue by john-griffin** [flynn-archive/go-discoverd#7]
When running discoverd in a docker container, docker exposes where it is running in an environment variable formatted like `tcp://172.17.0.36:1111`. Whereas go-discoverd expects the format to be `172.17.0.36:1111`. 

Is it worth tweaking this behaviour to be able to handle either style for compatibility with docker?

**Comment by titanous** [comment]
Yeah, I'm fine with this. `tcp://` isn't a real URI scheme, but there's no downside to supporting it. Do you want to open a pull request?
